
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Canvas, Entry, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def show_loginPage(window, switch_page, user_id):
    for widget in window.winfo_children():
        widget.destroy()
    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 1024,
        width = 1440,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        720.0,
        489.0,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        719.0,
        576.0,
        image=image_image_2
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        719.5,
        565.5,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=464.0,
        y=531.0,
        width=511.0,
        height=67.0
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: switch_page("mainLogined"),
        relief="flat"
    )
    button_1.place(
        x=564.0,
        y=664.0,
        width=312.0,
        height=69.0
    )

    canvas.create_text(
        497.0,
        444.0,
        anchor="nw",
        text="Please enter your ID to log in",
        fill="#000000",
        font=("Urbanist Regular", 36 * -1)
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: switch_page("main"),
        relief="flat"
    )
    button_2.place(
        x=1048.0,
        y=387.0,
        width=40.0,
        height=40.0
    )

    canvas.image_1 = image_image_1
    canvas.image_2 = image_image_2
    canvas.image_3 = entry_image_1
    canvas.image_4 = button_image_1
    canvas.image_5 = button_image_2
    canvas.button_1 = button_1
    canvas.button_2 = button_2
