
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Canvas, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def show_votePageLogined(window, switch_page):
    for widget in window.winfo_children():
            widget.destroy()
    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 1024,
        width = 1440,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        720.0,
        92.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: switch_page("main"),
        relief="flat"
    )
    button_1.place(
        x=1217.0,
        y=70.0,
        width=45.0,
        height=45.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=327.0,
        y=73.0,
        width=141.0,
        height=43.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: switch_page("mainLogined"),
        relief="flat"
    )
    button_3.place(
        x=164.0,
        y=73.0,
        width=141.0,
        height=43.0
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        720.0,
        421.0,
        image=image_image_2
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: switch_page("message", user_id=None),
        relief="flat"
    )
    button_4.place(
        x=564.0,
        y=700.0,
        width=312.0,
        height=69.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_5 clicked"),
        relief="flat"
    )
    button_5.place(
        x=147.0,
        y=632.0,
        width=196.0,
        height=52.0
    )

    button_image_6 = PhotoImage(
        file=relative_to_assets("button_6.png"))
    button_6 = Button(
        image=button_image_6,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_6 clicked"),
        relief="flat"
    )
    button_6.place(
        x=462.0,
        y=632.0,
        width=196.0,
        height=52.0
    )

    button_image_7 = PhotoImage(
        file=relative_to_assets("button_7.png"))
    button_7 = Button(
        image=button_image_7,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_7 clicked"),
        relief="flat"
    )
    button_7.place(
        x=780.0,
        y=632.0,
        width=196.0,
        height=52.0
    )

    button_image_8 = PhotoImage(
        file=relative_to_assets("button_8.png"))
    button_8 = Button(
        image=button_image_8,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_8 clicked"),
        relief="flat"
    )
    button_8.place(
        x=1098.0,
        y=632.0,
        width=196.0,
        height=52.0
    )
    canvas.image_1 = image_image_1
    canvas.image_2 = image_image_2
    canvas.image_3 = button_image_1
    canvas.image_4 = button_image_2
    canvas.image_5 = button_image_3
    canvas.image_6 = button_image_4
    canvas.image_7 = button_image_5
    canvas.image_8 = button_image_6
    canvas.image_9 = button_image_7
    canvas.image_10 = button_image_8
    canvas.button_1 = button_1
    canvas.button_2 = button_2
    canvas.button_3 = button_3
    canvas.button_4 = button_4
    canvas.button_5 = button_5
    canvas.button_6 = button_6
    canvas.button_7 = button_7
    canvas.button_8 = button_8
