
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Canvas, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)




def show_mainPageNotLogined(window, switch_page, user_id):

    for widget in window.winfo_children():
        widget.destroy()

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 1024,
        width = 1440,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        720.0,
        489.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=164.0,
        y=73.0,
        width=141.0,
        height=43.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: switch_page("login", user_id=None),
        relief="flat"
    )
    button_2.place(
        x=327.0,
        y=73.0,
        width=141.0,
        height=43.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: switch_page("login"),
        relief="flat"
    )
    button_3.place(
        x=1172.0,
        y=73.0,
        width=200.0,
        height=41.0
    )

    canvas.image_1 = image_image_1
    canvas.image_2 = button_image_1
    canvas.image_3 = button_image_2
    canvas.image_4 = button_image_3
    canvas.button_1 = button_1
    canvas.button_2 = button_2
    canvas.button_3 = button_3

